### ISSUE TITLE
Could not require package via composer

### ISSUE THREAD

**Issue by JacobBlana** [SebKay/wp-queued-jobs#19]
Hello, i wanted to test out your package for our import layer in WP theme. 
Unfortunately i didnt even manage to get it installed, because composer is reporting no package found.

![obrazek](https://user-images.githubusercontent.com/22232210/227930200-ae9a7df3-2d55-41d9-ba16-c9c118fbae66.png)

I checked it many times, the spelling is correct. Your all other packages seems available. Just this one isn't 😞 
![obrazek](https://user-images.githubusercontent.com/22232210/227990593-e4a9edcb-8657-4805-807c-1560a8e0c31e.png)

Thanks

**Comment by SebKay** [comment]
Hi,

Apologies for the issue!

Did you ever find out what was causing this or would you still like me to investigate?

**Comment by JacobBlana** [comment]
Hi,
looks like it is not publish to packagist https://packagist.org/?query=SebKay

In the end i installed it to composer as git repository. That worked.

**Comment by SebKay** [comment]
Ah, I see what you mean.

I've just added the package to packagist so this doesn't stop anyone else in the future https://packagist.org/packages/sebkay/wp-queued-jobs

Thanks for the heads up and sorry about that!
